image: adrianchan/maven-xvfb

before_script:
  - service xvfb start

stages:
  - test

test:
  script:
    # - wget http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar -q
    # - java -jar selenium-server-standalone-3.0.1.jar -role hub &
    # - sleep 10
    # - java -jar selenium-server-standalone-3.0.1.jar -role node -hub http://localhost:4444/grid/register/ -port 5566 -browser browserName=firefox,maxInstances=5 -browser browserName=chrome,maxInstances=5 -maxSession 5 &
    - mvn install:install-file -Dfile=src/main/java/dependencies/bdd-framework-utilities/bdd-framework-utilities-1.0-SNAPSHOT.jar -DpomFile=src/main/java/dependencies/bdd-framework-utilities/pom.xml -q
    - mvn install:install-file -Dfile=src/main/java/dependencies/cucumber-jvm-parallel-plugin/cucumber-jvm-parallel-plugin-2.1.1-SNAPSHOT.jar -DpomFile=src/main/java/dependencies/cucumber-jvm-parallel-plugin/pom.xml -q
    - mvn install:install-file -Dfile=src/main/java/dependencies/post-execution-updates-plugin/post-execution-updates-plugin-1.0-SNAPSHOT.jar -DpomFile=src/main/java/dependencies/post-execution-updates-plugin/pom.xml -q
    - mvn clean verify -q -Denv=local "-Dcucumber.options=--tags @regression"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - target/site/*
    expire_in: 1 week
